// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAlertsByStatus = `-- name: CountAlertsByStatus :many
SELECT status, COUNT(*) as count
FROM alerts
GROUP BY status
`

type CountAlertsByStatusRow struct {
	Status string
	Count  int64
}

func (q *Queries) CountAlertsByStatus(ctx context.Context) ([]CountAlertsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countAlertsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountAlertsByStatusRow
	for rows.Next() {
		var i CountAlertsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (
    id,
    indicator_id,
    event_id,
    severity,
    risk_score,
    confidence,
    title,
    description,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, indicator_id, event_id, severity, risk_score, confidence, title, description, status, created_at, resolved_at
`

type CreateAlertParams struct {
	ID          pgtype.UUID
	IndicatorID pgtype.UUID
	EventID     pgtype.UUID
	Severity    string
	RiskScore   float64
	Confidence  float64
	Title       string
	Description pgtype.Text
	Status      string
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createAlert,
		arg.ID,
		arg.IndicatorID,
		arg.EventID,
		arg.Severity,
		arg.RiskScore,
		arg.Confidence,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.IndicatorID,
		&i.EventID,
		&i.Severity,
		&i.RiskScore,
		&i.Confidence,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getAlertByID = `-- name: GetAlertByID :one
SELECT id, indicator_id, event_id, severity, risk_score, confidence, title, description, status, created_at, resolved_at FROM alerts
WHERE id = $1
`

func (q *Queries) GetAlertByID(ctx context.Context, id pgtype.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlertByID, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.IndicatorID,
		&i.EventID,
		&i.Severity,
		&i.RiskScore,
		&i.Confidence,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listAlerts = `-- name: ListAlerts :many
SELECT id, indicator_id, event_id, severity, risk_score, confidence, title, description, status, created_at, resolved_at FROM alerts
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAlertsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAlerts(ctx context.Context, arg ListAlertsParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlerts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.IndicatorID,
			&i.EventID,
			&i.Severity,
			&i.RiskScore,
			&i.Confidence,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsByStatus = `-- name: ListAlertsByStatus :many
SELECT id, indicator_id, event_id, severity, risk_score, confidence, title, description, status, created_at, resolved_at FROM alerts
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAlertsByStatusParams struct {
	Status string
	Limit  int32
	Offset int32
}

func (q *Queries) ListAlertsByStatus(ctx context.Context, arg ListAlertsByStatusParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.IndicatorID,
			&i.EventID,
			&i.Severity,
			&i.RiskScore,
			&i.Confidence,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertStatus = `-- name: UpdateAlertStatus :one
UPDATE alerts
SET
    status = $2,
    resolved_at = CASE WHEN $2 IN ('resolved', 'false_positive') THEN now() ELSE NULL END
WHERE id = $1
RETURNING id, indicator_id, event_id, severity, risk_score, confidence, title, description, status, created_at, resolved_at
`

type UpdateAlertStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateAlertStatus(ctx context.Context, arg UpdateAlertStatusParams) (Alert, error) {
	row := q.db.QueryRow(ctx, updateAlertStatus, arg.ID, arg.Status)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.IndicatorID,
		&i.EventID,
		&i.Severity,
		&i.RiskScore,
		&i.Confidence,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
