// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrichments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEnrichmentByProvider = `-- name: GetEnrichmentByProvider :one
SELECT id, indicator_id, provider, data, fetched_at, expires_at FROM enrichments
WHERE indicator_id = $1 AND provider = $2
`

type GetEnrichmentByProviderParams struct {
	IndicatorID pgtype.UUID
	Provider    string
}

func (q *Queries) GetEnrichmentByProvider(ctx context.Context, arg GetEnrichmentByProviderParams) (Enrichment, error) {
	row := q.db.QueryRow(ctx, getEnrichmentByProvider, arg.IndicatorID, arg.Provider)
	var i Enrichment
	err := row.Scan(
		&i.ID,
		&i.IndicatorID,
		&i.Provider,
		&i.Data,
		&i.FetchedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getEnrichmentsByIndicatorID = `-- name: GetEnrichmentsByIndicatorID :many
SELECT id, indicator_id, provider, data, fetched_at, expires_at FROM enrichments
WHERE indicator_id = $1
ORDER BY fetched_at DESC
`

func (q *Queries) GetEnrichmentsByIndicatorID(ctx context.Context, indicatorID pgtype.UUID) ([]Enrichment, error) {
	rows, err := q.db.Query(ctx, getEnrichmentsByIndicatorID, indicatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Enrichment
	for rows.Next() {
		var i Enrichment
		if err := rows.Scan(
			&i.ID,
			&i.IndicatorID,
			&i.Provider,
			&i.Data,
			&i.FetchedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnrichment = `-- name: UpsertEnrichment :one
INSERT INTO enrichments (
    id,
    indicator_id,
    provider,
    data,
    fetched_at,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (indicator_id, provider) DO UPDATE
SET
    data = EXCLUDED.data,
    fetched_at = EXCLUDED.fetched_at,
    expires_at = EXCLUDED.expires_at
RETURNING id, indicator_id, provider, data, fetched_at, expires_at
`

type UpsertEnrichmentParams struct {
	ID          pgtype.UUID
	IndicatorID pgtype.UUID
	Provider    string
	Data        []byte
	FetchedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) UpsertEnrichment(ctx context.Context, arg UpsertEnrichmentParams) (Enrichment, error) {
	row := q.db.QueryRow(ctx, upsertEnrichment,
		arg.ID,
		arg.IndicatorID,
		arg.Provider,
		arg.Data,
		arg.FetchedAt,
		arg.ExpiresAt,
	)
	var i Enrichment
	err := row.Scan(
		&i.ID,
		&i.IndicatorID,
		&i.Provider,
		&i.Data,
		&i.FetchedAt,
		&i.ExpiresAt,
	)
	return i, err
}
