// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEvents = `-- name: CountEvents :one
SELECT COUNT(*) FROM events
`

func (q *Queries) CountEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    id,
    timestamp,
    source,
    source_ip,
    destination_ip,
    source_port,
    destination_port,
    protocol,
    domain,
    url,
    file_hash,
    username,
    attack_type,
    severity,
    confidence,
    raw_payload
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id, timestamp, source, source_ip, destination_ip, source_port, destination_port, protocol, domain, url, file_hash, username, attack_type, severity, confidence, raw_payload, created_at
`

type CreateEventParams struct {
	ID              pgtype.UUID
	Timestamp       pgtype.Timestamptz
	Source          string
	SourceIp        *netip.Addr
	DestinationIp   *netip.Addr
	SourcePort      pgtype.Int4
	DestinationPort pgtype.Int4
	Protocol        pgtype.Text
	Domain          pgtype.Text
	Url             pgtype.Text
	FileHash        pgtype.Text
	Username        pgtype.Text
	AttackType      pgtype.Text
	Severity        string
	Confidence      float64
	RawPayload      []byte
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ID,
		arg.Timestamp,
		arg.Source,
		arg.SourceIp,
		arg.DestinationIp,
		arg.SourcePort,
		arg.DestinationPort,
		arg.Protocol,
		arg.Domain,
		arg.Url,
		arg.FileHash,
		arg.Username,
		arg.AttackType,
		arg.Severity,
		arg.Confidence,
		arg.RawPayload,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.Source,
		&i.SourceIp,
		&i.DestinationIp,
		&i.SourcePort,
		&i.DestinationPort,
		&i.Protocol,
		&i.Domain,
		&i.Url,
		&i.FileHash,
		&i.Username,
		&i.AttackType,
		&i.Severity,
		&i.Confidence,
		&i.RawPayload,
		&i.CreatedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, timestamp, source, source_ip, destination_ip, source_port, destination_port, protocol, domain, url, file_hash, username, attack_type, severity, confidence, raw_payload, created_at FROM events
WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.Source,
		&i.SourceIp,
		&i.DestinationIp,
		&i.SourcePort,
		&i.DestinationPort,
		&i.Protocol,
		&i.Domain,
		&i.Url,
		&i.FileHash,
		&i.Username,
		&i.AttackType,
		&i.Severity,
		&i.Confidence,
		&i.RawPayload,
		&i.CreatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, timestamp, source, source_ip, destination_ip, source_port, destination_port, protocol, domain, url, file_hash, username, attack_type, severity, confidence, raw_payload, created_at FROM events
ORDER BY timestamp DESC
LIMIT $1 OFFSET $2
`

type ListEventsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Source,
			&i.SourceIp,
			&i.DestinationIp,
			&i.SourcePort,
			&i.DestinationPort,
			&i.Protocol,
			&i.Domain,
			&i.Url,
			&i.FileHash,
			&i.Username,
			&i.AttackType,
			&i.Severity,
			&i.Confidence,
			&i.RawPayload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
