// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: indicators.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIndicators = `-- name: CountIndicators :one
SELECT COUNT(*) FROM indicators
`

func (q *Queries) CountIndicators(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countIndicators)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getIndicatorByID = `-- name: GetIndicatorByID :one
SELECT id, type, value, first_seen, last_seen, risk_score, confidence, status, created_at, updated_at FROM indicators
WHERE id = $1
`

func (q *Queries) GetIndicatorByID(ctx context.Context, id pgtype.UUID) (Indicator, error) {
	row := q.db.QueryRow(ctx, getIndicatorByID, id)
	var i Indicator
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Value,
		&i.FirstSeen,
		&i.LastSeen,
		&i.RiskScore,
		&i.Confidence,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIndicatorByTypeValue = `-- name: GetIndicatorByTypeValue :one
SELECT id, type, value, first_seen, last_seen, risk_score, confidence, status, created_at, updated_at FROM indicators
WHERE type = $1 AND value = $2
`

type GetIndicatorByTypeValueParams struct {
	Type  string
	Value string
}

func (q *Queries) GetIndicatorByTypeValue(ctx context.Context, arg GetIndicatorByTypeValueParams) (Indicator, error) {
	row := q.db.QueryRow(ctx, getIndicatorByTypeValue, arg.Type, arg.Value)
	var i Indicator
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Value,
		&i.FirstSeen,
		&i.LastSeen,
		&i.RiskScore,
		&i.Confidence,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIndicators = `-- name: ListIndicators :many
SELECT id, type, value, first_seen, last_seen, risk_score, confidence, status, created_at, updated_at FROM indicators
ORDER BY risk_score DESC, last_seen DESC
LIMIT $1 OFFSET $2
`

type ListIndicatorsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListIndicators(ctx context.Context, arg ListIndicatorsParams) ([]Indicator, error) {
	rows, err := q.db.Query(ctx, listIndicators, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Indicator
	for rows.Next() {
		var i Indicator
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Value,
			&i.FirstSeen,
			&i.LastSeen,
			&i.RiskScore,
			&i.Confidence,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIndicatorsByType = `-- name: ListIndicatorsByType :many
SELECT id, type, value, first_seen, last_seen, risk_score, confidence, status, created_at, updated_at FROM indicators
WHERE type = $1
ORDER BY risk_score DESC, last_seen DESC
LIMIT $2 OFFSET $3
`

type ListIndicatorsByTypeParams struct {
	Type   string
	Limit  int32
	Offset int32
}

func (q *Queries) ListIndicatorsByType(ctx context.Context, arg ListIndicatorsByTypeParams) ([]Indicator, error) {
	rows, err := q.db.Query(ctx, listIndicatorsByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Indicator
	for rows.Next() {
		var i Indicator
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Value,
			&i.FirstSeen,
			&i.LastSeen,
			&i.RiskScore,
			&i.Confidence,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIndicatorRiskScore = `-- name: UpdateIndicatorRiskScore :one
UPDATE indicators
SET
    risk_score = $2,
    confidence = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, type, value, first_seen, last_seen, risk_score, confidence, status, created_at, updated_at
`

type UpdateIndicatorRiskScoreParams struct {
	ID         pgtype.UUID
	RiskScore  float64
	Confidence float64
}

func (q *Queries) UpdateIndicatorRiskScore(ctx context.Context, arg UpdateIndicatorRiskScoreParams) (Indicator, error) {
	row := q.db.QueryRow(ctx, updateIndicatorRiskScore, arg.ID, arg.RiskScore, arg.Confidence)
	var i Indicator
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Value,
		&i.FirstSeen,
		&i.LastSeen,
		&i.RiskScore,
		&i.Confidence,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIndicator = `-- name: UpsertIndicator :one
INSERT INTO indicators (
    id,
    type,
    value,
    first_seen,
    last_seen,
    risk_score,
    confidence,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (type, value) DO UPDATE
SET
    last_seen = EXCLUDED.last_seen,
    risk_score = GREATEST(indicators.risk_score, EXCLUDED.risk_score),
    confidence = GREATEST(indicators.confidence, EXCLUDED.confidence),
    updated_at = now()
RETURNING id, type, value, first_seen, last_seen, risk_score, confidence, status, created_at, updated_at
`

type UpsertIndicatorParams struct {
	ID         pgtype.UUID
	Type       string
	Value      string
	FirstSeen  pgtype.Timestamptz
	LastSeen   pgtype.Timestamptz
	RiskScore  float64
	Confidence float64
	Status     string
}

func (q *Queries) UpsertIndicator(ctx context.Context, arg UpsertIndicatorParams) (Indicator, error) {
	row := q.db.QueryRow(ctx, upsertIndicator,
		arg.ID,
		arg.Type,
		arg.Value,
		arg.FirstSeen,
		arg.LastSeen,
		arg.RiskScore,
		arg.Confidence,
		arg.Status,
	)
	var i Indicator
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Value,
		&i.FirstSeen,
		&i.LastSeen,
		&i.RiskScore,
		&i.Confidence,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
