// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID          pgtype.UUID
	IndicatorID pgtype.UUID
	EventID     pgtype.UUID
	Severity    string
	RiskScore   float64
	Confidence  float64
	Title       string
	Description pgtype.Text
	Status      string
	CreatedAt   pgtype.Timestamptz
	ResolvedAt  pgtype.Timestamptz
}

type Enrichment struct {
	ID          pgtype.UUID
	IndicatorID pgtype.UUID
	Provider    string
	Data        []byte
	FetchedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

type Event struct {
	ID              pgtype.UUID
	Timestamp       pgtype.Timestamptz
	Source          string
	SourceIp        *netip.Addr
	DestinationIp   *netip.Addr
	SourcePort      pgtype.Int4
	DestinationPort pgtype.Int4
	Protocol        pgtype.Text
	Domain          pgtype.Text
	Url             pgtype.Text
	FileHash        pgtype.Text
	Username        pgtype.Text
	AttackType      pgtype.Text
	Severity        string
	Confidence      float64
	RawPayload      []byte
	CreatedAt       pgtype.Timestamptz
}

type Indicator struct {
	ID         pgtype.UUID
	Type       string
	Value      string
	FirstSeen  pgtype.Timestamptz
	LastSeen   pgtype.Timestamptz
	RiskScore  float64
	Confidence float64
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Observation struct {
	ID          pgtype.UUID
	IndicatorID pgtype.UUID
	EventID     pgtype.UUID
	AttackType  string
	TechniqueID pgtype.Text
	Timestamp   pgtype.Timestamptz
	Severity    string
	Confidence  float64
	Source      pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type Relationship struct {
	ID                pgtype.UUID
	SourceIndicatorID pgtype.UUID
	TargetIndicatorID pgtype.UUID
	RelationshipType  string
	Confidence        float64
	FirstSeen         pgtype.Timestamptz
	LastSeen          pgtype.Timestamptz
}
