// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: observations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createObservation = `-- name: CreateObservation :one
INSERT INTO observations (
    id,
    indicator_id,
    event_id,
    attack_type,
    technique_id,
    timestamp,
    severity,
    confidence,
    source
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, indicator_id, event_id, attack_type, technique_id, timestamp, severity, confidence, source, created_at
`

type CreateObservationParams struct {
	ID          pgtype.UUID
	IndicatorID pgtype.UUID
	EventID     pgtype.UUID
	AttackType  string
	TechniqueID pgtype.Text
	Timestamp   pgtype.Timestamptz
	Severity    string
	Confidence  float64
	Source      pgtype.Text
}

func (q *Queries) CreateObservation(ctx context.Context, arg CreateObservationParams) (Observation, error) {
	row := q.db.QueryRow(ctx, createObservation,
		arg.ID,
		arg.IndicatorID,
		arg.EventID,
		arg.AttackType,
		arg.TechniqueID,
		arg.Timestamp,
		arg.Severity,
		arg.Confidence,
		arg.Source,
	)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.IndicatorID,
		&i.EventID,
		&i.AttackType,
		&i.TechniqueID,
		&i.Timestamp,
		&i.Severity,
		&i.Confidence,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const listObservationsByEventID = `-- name: ListObservationsByEventID :many
SELECT id, indicator_id, event_id, attack_type, technique_id, timestamp, severity, confidence, source, created_at FROM observations
WHERE event_id = $1
ORDER BY timestamp DESC
`

func (q *Queries) ListObservationsByEventID(ctx context.Context, eventID pgtype.UUID) ([]Observation, error) {
	rows, err := q.db.Query(ctx, listObservationsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Observation
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ID,
			&i.IndicatorID,
			&i.EventID,
			&i.AttackType,
			&i.TechniqueID,
			&i.Timestamp,
			&i.Severity,
			&i.Confidence,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsByIndicatorID = `-- name: ListObservationsByIndicatorID :many
SELECT id, indicator_id, event_id, attack_type, technique_id, timestamp, severity, confidence, source, created_at FROM observations
WHERE indicator_id = $1
ORDER BY timestamp DESC
`

func (q *Queries) ListObservationsByIndicatorID(ctx context.Context, indicatorID pgtype.UUID) ([]Observation, error) {
	rows, err := q.db.Query(ctx, listObservationsByIndicatorID, indicatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Observation
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ID,
			&i.IndicatorID,
			&i.EventID,
			&i.AttackType,
			&i.TechniqueID,
			&i.Timestamp,
			&i.Severity,
			&i.Confidence,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
