// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relationships.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRelationshipsByIndicatorID = `-- name: GetRelationshipsByIndicatorID :many
SELECT id, source_indicator_id, target_indicator_id, relationship_type, confidence, first_seen, last_seen FROM relationships
WHERE source_indicator_id = $1 OR target_indicator_id = $1
ORDER BY last_seen DESC
`

func (q *Queries) GetRelationshipsByIndicatorID(ctx context.Context, sourceIndicatorID pgtype.UUID) ([]Relationship, error) {
	rows, err := q.db.Query(ctx, getRelationshipsByIndicatorID, sourceIndicatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Relationship
	for rows.Next() {
		var i Relationship
		if err := rows.Scan(
			&i.ID,
			&i.SourceIndicatorID,
			&i.TargetIndicatorID,
			&i.RelationshipType,
			&i.Confidence,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRelationship = `-- name: UpsertRelationship :one
INSERT INTO relationships (
    id,
    source_indicator_id,
    target_indicator_id,
    relationship_type,
    confidence,
    first_seen,
    last_seen
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (source_indicator_id, target_indicator_id, relationship_type) DO UPDATE
SET
    last_seen = EXCLUDED.last_seen,
    confidence = GREATEST(relationships.confidence, EXCLUDED.confidence)
RETURNING id, source_indicator_id, target_indicator_id, relationship_type, confidence, first_seen, last_seen
`

type UpsertRelationshipParams struct {
	ID                pgtype.UUID
	SourceIndicatorID pgtype.UUID
	TargetIndicatorID pgtype.UUID
	RelationshipType  string
	Confidence        float64
	FirstSeen         pgtype.Timestamptz
	LastSeen          pgtype.Timestamptz
}

func (q *Queries) UpsertRelationship(ctx context.Context, arg UpsertRelationshipParams) (Relationship, error) {
	row := q.db.QueryRow(ctx, upsertRelationship,
		arg.ID,
		arg.SourceIndicatorID,
		arg.TargetIndicatorID,
		arg.RelationshipType,
		arg.Confidence,
		arg.FirstSeen,
		arg.LastSeen,
	)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.SourceIndicatorID,
		&i.TargetIndicatorID,
		&i.RelationshipType,
		&i.Confidence,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}
