"use client"

import { useState, useEffect, useCallback } from "react"
import Link from "next/link"
import {
  AlertTriangle,
  RefreshCw,
  CheckCircle2,
  Clock,
  ShieldCheck,
  ExternalLink,
  ShieldAlert,
} from "lucide-react"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { SeverityBadge } from "@/components/dashboard/severity-badge"
import { RiskMeter } from "@/components/dashboard/risk-meter"
import { api } from "@/lib/api"
import type { Alert, AlertStatus } from "@/lib/types"

const STATUS_TABS: { label: string; value: string }[] = [
  { label: "All Alerts", value: "all" },
  { label: "Open (Active)", value: "open" },
  { label: "Investigating", value: "investigating" },
  { label: "Resolved", value: "resolved" },
  { label: "False Positive", value: "false_positive" },
]

export default function AlertsPage() {
  const [alerts, setAlerts] = useState<Alert[]>([])
  const [selectedStatus, setSelectedStatus] = useState<string>("all")
  const [isLoading, setIsLoading] = useState(true)
  const [updatingId, setUpdatingId] = useState<string | null>(null)

  const loadAlerts = useCallback(async () => {
    setIsLoading(true)
    try {
      const statusParam = selectedStatus === "all" ? undefined : selectedStatus
      const data = await api.getAlerts(statusParam, 50, 0)
      setAlerts(data || [])
    } catch (err) {
      console.error("Failed to load alerts:", err)
    } finally {
      setIsLoading(false)
    }
  }, [selectedStatus])

  useEffect(() => {
    loadAlerts()
  }, [loadAlerts])

  const handleStatusChange = async (alertId: string, newStatus: AlertStatus) => {
    setUpdatingId(alertId)
    try {
      await api.updateAlertStatus(alertId, newStatus)
      // Update local state optimistically
      setAlerts((prev) =>
        prev.map((a) =>
          a.id === alertId
            ? {
                ...a,
                status: newStatus,
                resolved_at: ["resolved", "false_positive"].includes(newStatus)
                  ? new Date().toISOString()
                  : undefined,
              }
            : a
        )
      )
    } catch (err) {
      console.error("Failed to update alert status:", err)
    } finally {
      setUpdatingId(null)
    }
  }

  const getStatusBadge = (status: AlertStatus) => {
    switch (status) {
      case "open":
        return <Badge variant="critical">Open</Badge>
      case "investigating":
        return <Badge variant="medium">Investigating</Badge>
      case "resolved":
        return <Badge variant="success">Resolved</Badge>
      case "false_positive":
        return <Badge variant="secondary">False Positive</Badge>
      default:
        return <Badge variant="outline">{status}</Badge>
    }
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-xl font-bold tracking-tight text-foreground flex items-center gap-2">
            <AlertTriangle className="size-5 text-red-400" />
            Alert Management Center
          </h1>
          <p className="text-xs text-muted-foreground">
            High and Critical threat alerts generated by autonomous risk threshold evaluation (Score ≥ 70).
          </p>
        </div>

        <Button
          variant="outline"
          size="sm"
          onClick={loadAlerts}
          disabled={isLoading}
          className="text-xs gap-1.5 h-8 border-border/60"
        >
          <RefreshCw className={`size-3 ${isLoading ? "animate-spin" : ""}`} />
          <span>Refresh</span>
        </Button>
      </div>

      {/* Status Filter Tabs */}
      <div className="flex flex-wrap items-center gap-1.5">
        {STATUS_TABS.map((tab) => (
          <Button
            key={tab.value}
            variant={selectedStatus === tab.value ? "default" : "outline"}
            size="xs"
            onClick={() => setSelectedStatus(tab.value)}
            className="text-xs h-7 border-border/60"
          >
            {tab.label}
          </Button>
        ))}
      </div>

      {/* Alerts List */}
      {isLoading ? (
        <Card className="p-12 text-center text-xs text-muted-foreground bg-card/50">
          <div className="flex items-center justify-center gap-2">
            <RefreshCw className="size-4 animate-spin text-primary" />
            <span>Loading security alerts...</span>
          </div>
        </Card>
      ) : alerts.length === 0 ? (
        <Card className="p-12 text-center text-xs text-muted-foreground bg-card/40 border-dashed space-y-2">
          <ShieldCheck className="size-8 text-emerald-400 mx-auto" />
          <div className="font-semibold text-foreground">No alerts matching filter</div>
          <p className="text-muted-foreground">
            All clear or no alerts matching &apos;{selectedStatus}&apos;.
          </p>
        </Card>
      ) : (
        <div className="grid grid-cols-1 gap-4">
          {alerts.map((alert) => (
            <Card
              key={alert.id}
              className="bg-card/80 border-border/60 hover:border-red-500/30 transition-colors p-5 space-y-4"
            >
              <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-3">
                <div className="space-y-1.5">
                  <div className="flex items-center gap-2">
                    <SeverityBadge severity={alert.severity} />
                    {getStatusBadge(alert.status)}
                    <span className="text-[0.65rem] font-mono text-muted-foreground">
                      {new Date(alert.created_at).toLocaleString()}
                    </span>
                  </div>
                  <h3 className="text-sm font-bold text-foreground">{alert.title}</h3>
                  {alert.description && (
                    <p className="text-xs text-muted-foreground">{alert.description}</p>
                  )}
                </div>

                <div className="w-48 shrink-0">
                  <RiskMeter score={alert.risk_score} showBar={true} />
                  <div className="text-[0.65rem] font-mono text-muted-foreground text-right mt-1">
                    Confidence: {Math.round(alert.confidence * 100)}%
                  </div>
                </div>
              </div>

              {/* Action Controls & Workflow State */}
              <div className="flex flex-wrap items-center justify-between border-t border-border/40 pt-3 gap-2">
                <div className="flex items-center gap-1.5">
                  <span className="text-[0.65rem] text-muted-foreground mr-1">Triage:</span>

                  {alert.status !== "investigating" && (
                    <Button
                      variant="outline"
                      size="xs"
                      disabled={updatingId === alert.id}
                      onClick={() => handleStatusChange(alert.id, "investigating")}
                      className="text-[0.65rem] h-6 border-amber-500/30 text-amber-400 hover:bg-amber-500/10"
                    >
                      Investigating
                    </Button>
                  )}

                  {alert.status !== "resolved" && (
                    <Button
                      variant="outline"
                      size="xs"
                      disabled={updatingId === alert.id}
                      onClick={() => handleStatusChange(alert.id, "resolved")}
                      className="text-[0.65rem] h-6 border-emerald-500/30 text-emerald-400 hover:bg-emerald-500/10"
                    >
                      Resolve
                    </Button>
                  )}

                  {alert.status !== "false_positive" && (
                    <Button
                      variant="outline"
                      size="xs"
                      disabled={updatingId === alert.id}
                      onClick={() => handleStatusChange(alert.id, "false_positive")}
                      className="text-[0.65rem] h-6 border-border/60 text-muted-foreground hover:bg-muted"
                    >
                      False Positive
                    </Button>
                  )}
                </div>

                <Link href="/indicators">
                  <Button variant="ghost" size="xs" className="gap-1 text-[0.65rem]">
                    <span>View Indicators</span>
                    <ExternalLink className="size-2.5" />
                  </Button>
                </Link>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  )
}
